[package]
name = "rekognition"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-rekognition = "1.35.0"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
